language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: api-node-example-continuos
  api_key:
    secure: kCRz2puoudOxSfjCjT1tSv5KW4MY+22uro7fYi4mT0CFq5qNAAGkYZE8ZDQ0hZNNdusTP7Az6e0GZNLFRjIWDxX2oonfUsZC2fr6fARNrG2WYomhTByadoLU0ewFT+xH9pTuwIXJBGVOzCDw78304wUlGiBw/GQcWURXST1NkoZ1pg+arKrRKk40dehbbRdRZlUcC11pdg5C2GPOiGfTEXTcTh7LLC+FjMyAygxFcF0bKtidgUrN3g870i7TFL3zULz8659BbTiMaP+Zi+xN27kAogDuxQg+aYp2XIQNHWL+xEILeJpw2fLkZ8U0Fc7b7HQWJAzMcKc5GLqxJx0GqBvTaJTQuVn11UQnAEEeAanevPfz3C9RyO8kwHot0Z9DB3cf1/PBz2QLxf16PRhqOtVFbkPxAT/Ld0D+8m4nbwp/pQQA2brdcSxAJk7amHSlgkNlfv1qq8lEIOFDVEryIsga8kDbDCzvM4NwrGC1QH9wTgpPJfja8qkoewaCnDxP3xPdeMmDydmfZvZrFYHqrvdlrnXFHvg981ET3EijWFEhCq2gq35t9SVza4ae77dJi2+YiRbftfStFsVXXoPEYAmAw+ZoJ4b5eR1IQfvHWe0NVxoAYG807GAVcABxIJm91O/Bv4jSSIj4CKSn8xqAm//PTCqz2V2h5bHPvcty3F8=
